### ISSUE TITLE
review analytics, add tickets for untracked events

### ISSUE THREAD

**Issue by eads** [nprapps/bestsongs15-midyear#71]

**Comment by dannydb** [comment]
did a cleanup sweep to update the tracking to our current method, added the obvious stuff we missed and fixed the broken songs-played tracking

| Category | Action | Label | Value |
| --- | --- | --- | --- |
| bestsongs15-midyear | skip-intro |  |  |
| bestsongs15-midyear | render-ad |  |  |
| bestsongs15-midyear | songs-played |  | 5 |
| bestsongs15-midyear | filter-panel-open |  |  |
| bestsongs15-midyear | filter-panel-close |  |  |
| bestsongs15-midyear | song-skip | `artist`-`title` |  |
| bestsongs15-midyear | tag-finish | `selected-tag` |  |
| bestsongs15-midyear | switch-tag | `selected-tag` |  |
| bestsongs15-midyear | shuffle |  |  |
| bestsongs15-midyear | shuffle-clean |  |  |
| bestsongs15-midyear | explicit-language-on |  |  |
| bestsongs15-midyear | explicit-language-off |  |  |
| bestsongs15-midyear | continue-playback-click |  |  |
| bestsongs15-midyear | song-card-expand |  |  |
| bestsongs15-midyear | song-card-shrink |  |  |
| bestsongs15-midyear | show-history-click |  |  |
| bestsongs15-midyear | amazon-click | `song` |  |
| bestsongs15-midyear | itunes-click | `song` |  |
| bestsongs15-midyear | rdio-click | `song` |  |
| bestsongs15-midyear | spotify-click | `song` |  |
| bestsongs15-midyear | tweet | `location` |  |
| bestsongs15-midyear | facebook | `location` |  |
| bestsongs15-midyear | email | `location` |  |
| bestsongs15-midyear | new-comment |  |  |
| bestsongs15-midyear | share-discuss-open |  |  |
| bestsongs15-midyear | share-discuss-close |  |  |
| bestsongs15-midyear | summary-copied |  |  |
| bestsongs15-midyear | featured-tweet-action | `action` |  |
| bestsongs15-midyear | featured-facebook-action | `action` |  |
